### ISSUE TITLE
Sensordatamanager.jar unable to open or use in project

### ISSUE THREAD

**Issue by pjhartin** [xsenselabs/SensorDataManager#4]
Using android studio I get the following when trying to use the datamanager jar as a library:
<i>
Error:error reading /MYAPPPATH/libs/sensordatamanager.jar; error in opening zip file
ncProject">Re-download dependencies and sync project (requires network)</a>
</i>
Can you double check the .jar that is currently uploaded in bin? 

Thanks

**Comment by nlathia** [comment]
Hey @pjhartin, sorry for the late reply. I've just pushed a new .jar up. Thanks!
